-- Banua360 - Postgres (Supabase) schema, translated from server/db.js.
--
-- Run this ONCE against the Supabase database before scripts/migrate-to-postgres.js:
--   psql "$DATABASE_URL" -f scripts/postgres-schema.sql
-- or paste it into the Supabase SQL Editor.
--
-- Translation choices, so nobody has to re-derive them later:
--
--  * INTEGER PRIMARY KEY AUTOINCREMENT -> bigint GENERATED BY DEFAULT AS IDENTITY.
--    "BY DEFAULT" (not "ALWAYS") on purpose: the migration copies existing id
--    values so foreign keys keep pointing at the right rows. The migration
--    resets each sequence afterwards.
--  * REAL -> double precision, TEXT -> text, CHECK constraints copied verbatim.
--  * Timestamps stay `text` (ISO-8601 strings), exactly as SQLite stored them.
--    Converting to timestamptz would be an improvement, but it would change what
--    every query and every JSON response returns - a separate decision, not
--    something to smuggle into a migration.
--  * `aktif` and `ditemukan` stay integer rather than becoming boolean, for the
--    same reason: the app compares them numerically today.
--
-- Deliberately NOT here: the rpkp_completeness_item seed rows from db.js. They
-- are ordinary rows and the migration copies them across like any other data.

BEGIN;

CREATE TABLE IF NOT EXISTS desa (
  kode_desa         text PRIMARY KEY,
  provinsi          text,
  kabupaten         text,
  kecamatan         text,
  nama_desa         text,
  status_desa       text,
  lat               double precision,
  lng               double precision,
  tahun             integer,
  nilai_indeks_desa double precision
);

CREATE TABLE IF NOT EXISTS skor_indikator (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_desa      text NOT NULL REFERENCES desa (kode_desa),
  tahun          integer,
  dimensi        text,
  sub_dimensi    text,
  nama_indikator text,
  skor           double precision,
  bobot_maks     double precision
);
CREATE INDEX IF NOT EXISTS idx_skor_desa ON skor_indikator (kode_desa);

CREATE TABLE IF NOT EXISTS jawaban_kuesioner (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_desa  text NOT NULL REFERENCES desa (kode_desa),
  tahun      integer,
  pertanyaan text,
  jawaban    text
);
CREATE INDEX IF NOT EXISTS idx_jawaban_desa ON jawaban_kuesioner (kode_desa);

-- Rows recording the ABSENCE of a potensi ('Tidak Ada', '-', '') are not
-- migrated - every read path in index.js already filters them out. See
-- POTENSI_KOSONG in scripts/import-excel.js.
CREATE TABLE IF NOT EXISTS potensi_desa (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_desa text NOT NULL REFERENCES desa (kode_desa),
  tahun     integer,
  sektor    text,
  subsektor text,
  nilai     text
);
CREATE INDEX IF NOT EXISTS idx_potensi_desa ON potensi_desa (kode_desa);
CREATE INDEX IF NOT EXISTS idx_potensi_sektor ON potensi_desa (sektor);

CREATE TABLE IF NOT EXISTS ekosistem_desa (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_desa text NOT NULL REFERENCES desa (kode_desa),
  tahun     integer,
  komponen  text,
  nilai     text
);
CREATE INDEX IF NOT EXISTS idx_ekosistem_desa ON ekosistem_desa (kode_desa);

CREATE TABLE IF NOT EXISTS import_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sumber_file  text,
  sheet        text,
  waktu_import text,
  jumlah_baris integer
);

CREATE TABLE IF NOT EXISTS rekomendasi_produk (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_desa        text NOT NULL REFERENCES desa (kode_desa),
  input_hash       text NOT NULL,
  model            text,
  rekomendasi_json text,
  dibuat_pada      text
);
CREATE INDEX IF NOT EXISTS idx_rekomendasi_desa ON rekomendasi_produk (kode_desa, input_hash);

CREATE TABLE IF NOT EXISTS narasi_desa (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_desa   text NOT NULL REFERENCES desa (kode_desa),
  dimensi     text NOT NULL,
  input_hash  text NOT NULL,
  model       text,
  narasi      text,
  dibuat_pada text
);
CREATE INDEX IF NOT EXISTS idx_narasi_desa ON narasi_desa (kode_desa, dimensi, input_hash);

CREATE TABLE IF NOT EXISTS narasi_indeks (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scope_key   text NOT NULL,
  input_hash  text NOT NULL,
  model       text,
  hasil_json  text,
  dibuat_pada text
);
CREATE INDEX IF NOT EXISTS idx_narasi_indeks ON narasi_indeks (scope_key, input_hash);

CREATE TABLE IF NOT EXISTS rekomendasi_kabupaten (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kabupaten        text NOT NULL,
  input_hash       text NOT NULL,
  model            text,
  rekomendasi_json text,
  dibuat_pada      text
);
CREATE INDEX IF NOT EXISTS idx_rekomendasi_kab ON rekomendasi_kabupaten (kabupaten, input_hash);

CREATE TABLE IF NOT EXISTS kode_registrasi (
  id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode                 text UNIQUE NOT NULL,
  role                 text NOT NULL CHECK (role IN ('desa', 'kabupaten', 'provinsi', 'admin')),
  kode_desa            text REFERENCES desa (kode_desa),
  kabupaten            text,
  dibuat_oleh          text,
  dibuat_pada          text NOT NULL,
  dipakai_oleh_user_id integer,
  dipakai_pada         text
);
CREATE INDEX IF NOT EXISTS idx_kode_registrasi_kode ON kode_registrasi (kode);

CREATE TABLE IF NOT EXISTS users (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          text UNIQUE NOT NULL,
  nama           text,
  role           text NOT NULL CHECK (role IN ('desa', 'kabupaten', 'provinsi', 'admin')),
  kode_desa      text REFERENCES desa (kode_desa),
  kabupaten      text,
  dibuat_pada    text NOT NULL,
  login_terakhir text
);

CREATE TABLE IF NOT EXISTS rpkp_review (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_kawasan     text NOT NULL,
  kabupaten        text NOT NULL,
  periode          text,
  tahun_dokumen    integer,
  keterangan       text,
  status           text NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'NEED_CLARIFICATION', 'REVIEW_COMPLETED')),
  dibuat_oleh      text NOT NULL,
  dibuat_pada      text NOT NULL,
  diperbarui_pada  text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rpkp_review_kabupaten ON rpkp_review (kabupaten);

CREATE TABLE IF NOT EXISTS rpkp_document (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id              bigint NOT NULL REFERENCES rpkp_review (id),
  document_type          text NOT NULL,
  version                integer NOT NULL,
  original_filename      text NOT NULL,
  stored_filename        text NOT NULL,
  file_size              bigint,
  mime_type              text,
  diunggah_oleh          text NOT NULL,
  diunggah_pada          text NOT NULL,
  gemini_file_uri        text,
  gemini_file_expires_at text
);
CREATE INDEX IF NOT EXISTS idx_rpkp_document_review ON rpkp_document (review_id);

CREATE TABLE IF NOT EXISTS rpkp_review_history (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id   bigint NOT NULL REFERENCES rpkp_review (id),
  event_type  text NOT NULL,
  detail      text,
  aktor       text NOT NULL,
  dibuat_pada text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rpkp_history_review ON rpkp_review_history (review_id);

CREATE TABLE IF NOT EXISTS rpkp_ai_qa (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id      bigint NOT NULL REFERENCES rpkp_review (id),
  pertanyaan     text NOT NULL,
  ditemukan      integer NOT NULL,
  jawaban        text,
  sumber_dokumen text,
  halaman        integer,
  kutipan        text,
  model          text,
  prompt_version text,
  ditanya_oleh   text NOT NULL,
  dibuat_pada    text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rpkp_ai_qa_review ON rpkp_ai_qa (review_id);

CREATE TABLE IF NOT EXISTS rpkp_completeness_item (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode      text UNIQUE NOT NULL,
  kategori  text NOT NULL DEFAULT 'COMPLETENESS'
    CHECK (kategori IN ('COMPLETENESS', 'IPKP', 'READINESS')),
  label     text NOT NULL,
  deskripsi text,
  urutan    integer NOT NULL DEFAULT 0,
  aktif     integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rpkp_finding (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id       bigint NOT NULL REFERENCES rpkp_review (id),
  category        text NOT NULL
    CHECK (category IN ('COMPLETENESS', 'IPKP', 'READINESS', 'RTRW', 'RPJMD', 'BANUA360')),
  item_kode       text,
  title           text NOT NULL,
  ai_status       text NOT NULL CHECK (ai_status IN ('FOUND', 'PARTIAL', 'NOT_FOUND')),
  ai_summary      text,
  reviewer_status text NOT NULL DEFAULT 'PENDING'
    CHECK (reviewer_status IN ('PENDING', 'VERIFIED', 'REJECTED')),
  reviewer_note   text,
  model           text,
  prompt_version  text,
  dibuat_pada     text NOT NULL,
  diperbarui_pada text NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rpkp_finding_review ON rpkp_finding (review_id, category);

CREATE TABLE IF NOT EXISTS rpkp_evidence (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  finding_id     bigint NOT NULL REFERENCES rpkp_finding (id),
  document_id    bigint REFERENCES rpkp_document (id),
  sumber_dokumen text,
  halaman        integer,
  kutipan        text
);
CREATE INDEX IF NOT EXISTS idx_rpkp_evidence_finding ON rpkp_evidence (finding_id);

CREATE TABLE IF NOT EXISTS rpkp_recommendation (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id   bigint UNIQUE NOT NULL REFERENCES rpkp_review (id),
  keputusan   text NOT NULL
    CHECK (keputusan IN ('DAPAT_DIREKOMENDASIKAN', 'DENGAN_CATATAN', 'BELUM_DAPAT')),
  catatan     text,
  dibuat_oleh text NOT NULL,
  dibuat_pada text NOT NULL
);

CREATE TABLE IF NOT EXISTS rpkp_review_desa (
  review_id bigint NOT NULL REFERENCES rpkp_review (id),
  kode_desa text NOT NULL REFERENCES desa (kode_desa),
  PRIMARY KEY (review_id, kode_desa)
);

COMMIT;

-- Foreign keys must be DEFERRABLE for scripts/import-excel.js, which deletes
-- and re-inserts the same kode_desa set inside one transaction. Between the
-- DELETE and the re-INSERT the references from users/kode_registrasi are
-- briefly dangling, which is fine as long as they hold at COMMIT. SQLite did
-- this with `PRAGMA foreign_keys = OFF`; Postgres has no such switch for a
-- normal user, so the constraints are made deferrable instead.
--
-- INITIALLY IMMEDIATE keeps the normal behaviour: checks still run per
-- statement unless a transaction explicitly asks for SET CONSTRAINTS DEFERRED.
-- Idempotent, and safe to run against a database that already has data.
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT conrelid::regclass AS tbl, conname
      FROM pg_constraint
     WHERE contype = 'f'
       AND connamespace = 'public'::regnamespace
       AND NOT condeferrable
  LOOP
    EXECUTE format(
      'ALTER TABLE %s ALTER CONSTRAINT %I DEFERRABLE INITIALLY IMMEDIATE',
      r.tbl, r.conname
    );
  END LOOP;
END $$;
